version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2204:2022.04.2
   steps:
     - checkout
     - run: docker login --username amansingh2708 --password Maplelabs5678$
     # build the application image 
     - run: docker build -t amansingh2708/sf-scheduler:circitest ./sf-scheduler-code
     # deploy the image
     - run: docker push amansingh2708/sf-scheduler:circitest
 lint:
   docker:
     - image: golangci/golangci-lint:v1.37-alpine
   steps:
     - checkout
     - run: golangci-lint run
workflows:
  build_lint_test:
    jobs:
      - build
      