apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sf-scheduler.fullname" . }}-configmap
data:
  sf-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: sf-scheduler
      plugins:
        score:
          disabled:
          - name: '*'
          enabled:
          - name: NodeAffinity
          - name: TaintToleration
          - name: NodeResourcesLeastAllocated
          - name: InterPodAffinity
          - name: PodTopologySpread
    leaderElection:
      leaderElect: false